import {
  encodeBase64Utf8,
  escapeSurgeHeader,
  formatHostForUrl,
  sanitizeSurgeName,
  yamlQuote,
} from './helpers.js';
import type { ParsedNode, SubscriptionTarget } from './types.js';

const DEFAULT_TEST_URL = 'http://cp.cloudflare.com/generate_204';

export interface RenderResult {
  body: string;
  contentType: string;
  filename: string;
}

export function renderSubscription(
  target: SubscriptionTarget,
  nodes: ParsedNode[],
  requestUrl: string,
): RenderResult {
  switch (target) {
    case 'v2rayn':
    case 'shadowrocket':
      return renderRawSubscription(nodes);
    case 'clash':
      return renderClashSubscription(nodes);
    case 'surge':
      return renderSurgeSubscription(nodes, requestUrl);
  }
}

function renderRawSubscription(nodes: ParsedNode[]): RenderResult {
  const lines = nodes.map((node) => renderNodeUri(node)).join('\n');
  return {
    body: encodeBase64Utf8(lines),
    contentType: 'text/plain; charset=utf-8',
    filename: 'subscription.txt',
  };
}

function renderNodeUri(node: ParsedNode): string {
  switch (node.type) {
    case 'vmess':
      return renderVmessUri(node);
    case 'vless':
      return renderVlessUri(node);
    case 'trojan':
      return renderTrojanUri(node);
  }
}

function renderVmessUri(node: ParsedNode): string {
  const payload = {
    v: '2',
    ps: node.name,
    add: node.server,
    port: String(node.port),
    id: node.uuid,
    aid: String(node.alterId ?? 0),
    scy: node.cipher || 'auto',
    net: node.network || 'ws',
    type: node.headerType || '',
    host: node.hostHeader || '',
    path: node.path || '/',
    tls: node.tls ? (node.security || 'tls') : '',
    sni: node.sni || '',
    fp: node.fp || '',
    alpn: node.alpn?.length ? node.alpn.join(',') : '',
  };
  return `vmess://${encodeBase64Utf8(JSON.stringify(payload))}`;
}

function renderVlessUri(node: ParsedNode): string {
  const params = new URLSearchParams(node.params ?? {});
  params.set('type', node.network || 'ws');
  params.set('encryption', node.encryption || 'none');
  if (node.security) {
    params.set('security', node.security);
  } else if (node.tls) {
    params.set('security', 'tls');
  } else {
    params.delete('security');
  }
  setIfPresent(params, 'path', node.path);
  setIfPresent(params, 'host', node.hostHeader);
  setIfPresent(params, 'sni', node.sni);
  setIfPresent(params, 'alpn', node.alpn?.length ? node.alpn.join(',') : '');
  setIfPresent(params, 'fp', node.fp);
  setIfPresent(params, 'flow', node.flow);
  setIfPresent(params, 'serviceName', node.serviceName);
  setIfPresent(params, 'authority', node.authority);
  const hash = node.name ? `#${encodeURIComponent(node.name)}` : '';
  return `vless://${encodeURIComponent(node.uuid!)}@${formatHostForUrl(node.server)}:${node.port}?${params.toString()}${hash}`;
}

function renderTrojanUri(node: ParsedNode): string {
  const params = new URLSearchParams(node.params ?? {});
  params.set('type', node.network || 'ws');
  params.set('security', node.security || 'tls');
  setIfPresent(params, 'path', node.path);
  setIfPresent(params, 'host', node.hostHeader);
  setIfPresent(params, 'sni', node.sni);
  setIfPresent(params, 'alpn', node.alpn?.length ? node.alpn.join(',') : '');
  setIfPresent(params, 'fp', node.fp);
  setIfPresent(params, 'serviceName', node.serviceName);
  setIfPresent(params, 'authority', node.authority);
  const hash = node.name ? `#${encodeURIComponent(node.name)}` : '';
  return `trojan://${encodeURIComponent(node.password!)}@${formatHostForUrl(node.server)}:${node.port}?${params.toString()}${hash}`;
}

function setIfPresent(params: URLSearchParams, key: string, value: string | undefined): void {
  const normalized = String(value ?? '').trim();
  if (normalized) {
    params.set(key, normalized);
  } else {
    params.delete(key);
  }
}

function renderClashSubscription(nodes: ParsedNode[]): RenderResult {
  const supported = nodes.filter((node) => ['vmess', 'vless', 'trojan'].includes(node.type));
  if (!supported.length) {
    throw new Error('没有可导出为 Clash 的节点。');
  }

  const proxyNames = supported.map((node) => node.name);
  const lines = [
    '# Generated by CloudflareSub Next',
    'mixed-port: 7890',
    'allow-lan: false',
    'mode: rule',
    'log-level: info',
    'ipv6: false',
    'proxies:',
  ];

  supported.forEach((node) => {
    lines.push(...renderClashProxy(node));
  });

  lines.push('proxy-groups:');
  lines.push('  - name: "🚀 节点选择"');
  lines.push('    type: select');
  lines.push(`    proxies: ["♻️ 自动选择", ${proxyNames.map(yamlQuote).join(', ')}]`);
  lines.push('  - name: "♻️ 自动选择"');
  lines.push('    type: url-test');
  lines.push(`    url: ${yamlQuote(DEFAULT_TEST_URL)}`);
  lines.push('    interval: 300');
  lines.push('    tolerance: 50');
  lines.push(`    proxies: [${proxyNames.map(yamlQuote).join(', ')}]`);
  lines.push('rules:');
  lines.push('  - MATCH,🚀 节点选择');

  return {
    body: `${lines.join('\n')}\n`,
    contentType: 'text/yaml; charset=utf-8',
    filename: 'subscription-clash.yaml',
  };
}

function renderClashProxy(node: ParsedNode): string[] {
  const lines = [`  - name: ${yamlQuote(node.name)}`, `    type: ${node.type}`];
  lines.push(`    server: ${yamlQuote(node.server)}`);
  lines.push(`    port: ${node.port}`);
  lines.push('    udp: true');

  if (node.type === 'vmess') {
    lines.push(`    uuid: ${yamlQuote(node.uuid!)}`);
    lines.push(`    alterId: ${node.alterId ?? 0}`);
    lines.push(`    cipher: ${yamlQuote(node.cipher || 'auto')}`);
  }
  if (node.type === 'vless') {
    lines.push(`    uuid: ${yamlQuote(node.uuid!)}`);
    if (node.flow) {
      lines.push(`    flow: ${yamlQuote(node.flow)}`);
    }
  }
  if (node.type === 'trojan') {
    lines.push(`    password: ${yamlQuote(node.password!)}`);
  }

  if (node.tls) {
    lines.push('    tls: true');
    const servername = node.sni || node.hostHeader || node.originalServer;
    if (servername) {
      lines.push(`    servername: ${yamlQuote(servername)}`);
    }
    if (node.alpn?.length) {
      lines.push(`    alpn: [${node.alpn.map(yamlQuote).join(', ')}]`);
    }
    if (node.fp) {
      lines.push(`    client-fingerprint: ${yamlQuote(node.fp)}`);
    }
    lines.push(`    skip-cert-verify: ${node.allowInsecure ? 'true' : 'false'}`);
  }

  lines.push(`    network: ${node.network || 'tcp'}`);

  if (node.network === 'ws') {
    lines.push('    ws-opts:');
    lines.push(`      path: ${yamlQuote(node.path || '/')}`);
    if (node.hostHeader) {
      lines.push('      headers:');
      lines.push(`        Host: ${yamlQuote(node.hostHeader)}`);
    }
  }

  if (node.network === 'grpc') {
    lines.push('    grpc-opts:');
    lines.push(`      grpc-service-name: ${yamlQuote(node.serviceName || '')}`);
  }

  if (node.network === 'http' || node.network === 'h2') {
    lines.push('    http-opts:');
    lines.push(`      path: [${yamlQuote(node.path || '/')}]`);
    if (node.hostHeader) {
      lines.push('      headers:');
      lines.push(`        Host: [${yamlQuote(node.hostHeader)}]`);
    }
  }

  return lines;
}

function renderSurgeSubscription(nodes: ParsedNode[], requestUrl: string): RenderResult {
  const supported = nodes.filter((node) => node.type === 'vmess' || node.type === 'trojan');
  if (!supported.length) {
    throw new Error('当前 Surge 导出仅支持 VMess / Trojan 节点。');
  }

  const proxyNames = supported.map((node) => sanitizeSurgeName(node.name));
  const lines = [
    `#!MANAGED-CONFIG ${requestUrl} interval=86400 strict=false`,
    '',
    '[General]',
    'loglevel = notify',
    `internet-test-url = ${DEFAULT_TEST_URL}`,
    `proxy-test-url = ${DEFAULT_TEST_URL}`,
    'ipv6 = false',
    '',
    '[Proxy]',
  ];

  supported.forEach((node) => {
    lines.push(renderSurgeProxy(node));
  });

  lines.push('');
  lines.push('[Proxy Group]');
  lines.push(`🚀 节点选择 = select, ♻️ 自动选择, ${proxyNames.join(', ')}`);
  lines.push(`♻️ 自动选择 = url-test, ${proxyNames.join(', ')}, url=${DEFAULT_TEST_URL}, interval=600, tolerance=50`);
  lines.push('');
  lines.push('[Rule]');
  lines.push('FINAL, 🚀 节点选择');
  lines.push('');

  return {
    body: lines.join('\n'),
    contentType: 'text/plain; charset=utf-8',
    filename: 'subscription-surge.conf',
  };
}

function renderSurgeProxy(node: ParsedNode): string {
  const name = sanitizeSurgeName(node.name);
  const sni = node.sni || node.hostHeader || node.originalServer;

  if (node.type === 'vmess') {
    const params = [
      `username=${node.uuid}`,
      'vmess-aead=true',
      `tls=${node.tls ? 'true' : 'false'}`,
      `skip-cert-verify=${node.allowInsecure ? 'true' : 'false'}`,
    ];
    if (sni) {
      params.push(`sni=${sni}`);
    }
    if (node.network === 'ws') {
      params.push('ws=true');
      params.push(`ws-path=${node.path || '/'}`);
      if (node.hostHeader) {
        params.push(`ws-headers=Host:"${escapeSurgeHeader(node.hostHeader)}"`);
      }
    }
    return `${name} = vmess, ${formatHostForUrl(node.server)}, ${node.port}, ${params.join(', ')}`;
  }

  const trojanParams = [
    `password=${node.password}`,
    `skip-cert-verify=${node.allowInsecure ? 'true' : 'false'}`,
  ];
  if (sni) {
    trojanParams.push(`sni=${sni}`);
  }
  if (node.network === 'ws') {
    trojanParams.push('ws=true');
    trojanParams.push(`ws-path=${node.path || '/'}`);
    if (node.hostHeader) {
      trojanParams.push(`ws-headers=Host:"${escapeSurgeHeader(node.hostHeader)}"`);
    }
  }
  return `${name} = trojan, ${formatHostForUrl(node.server)}, ${node.port}, ${trojanParams.join(', ')}`;
}
